package seedu.address.model.person;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import seedu.address.testutil.PersonBuilder;

/**
 * Tests substring matching across person fields.
 * This test class was generated by OpenAI Codex.
 */
public class AnyFieldContainsSubstringPredicateTest {

    private final Person person = new PersonBuilder().withName("Alex Yeoh").withPhone("91234567")
            .withEmail("alex@example.com").withAddress("123 Main Street").withTags("colleagues").build();

    @Test
    public void test_fieldContainsSubstring_returnsTrue() {
        // Partial matches in each supported field
        assertTrue(new AnyFieldContainsSubstringPredicate("Ye").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("2345").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("@example").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("Main").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("leagu").test(person));
    }

    @Test
    public void test_mixedCaseSubstring_returnsTrue() {
        assertTrue(new AnyFieldContainsSubstringPredicate("yEOh").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("@EXAMPLE").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("mAIN sTREET").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("LEAGU").test(person));
    }

    @Test
    public void test_multipleWords_matchesContiguousSubstringOnly() {
        assertTrue(new AnyFieldContainsSubstringPredicate("lex Yeo").test(person));
        assertTrue(new AnyFieldContainsSubstringPredicate("Main Street").test(person));
        assertFalse(new AnyFieldContainsSubstringPredicate("Alex Street").test(person));
        assertFalse(new AnyFieldContainsSubstringPredicate("Yeoh Alex").test(person));
    }

    @Test
    public void test_noFieldContainsSubstring_returnsFalse() {
        assertFalse(new AnyFieldContainsSubstringPredicate("Zachary").test(person));
        assertFalse(new AnyFieldContainsSubstringPredicate("9999").test(person));
        assertFalse(new AnyFieldContainsSubstringPredicate("@missing.org").test(person));
    }
}
